"""Dimensões e espaçamentos padronizados da GUI."""

MARGIN = 16
SECTION_SPACING = 12
CONTROL_SPACING = 8
BUTTON_HEIGHT = 34
MIN_BUTTON_WIDTH = 110
PROGRESS_HEIGHT = 20
FOOTER_HEIGHT = 28
SPLITTER_MIN = 180
