[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mame-set-builder"
version = "1.0.0"
description = "Aplicação desktop para gerenciamento, filtragem, validação e construção de conjuntos personalizados de ROMs para MAME"
readme = "README.md"
authors = [{ name = "Leonardo" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows",
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Games/Entertainment :: Arcade"
]
requires-python = ">=3.10"
dependencies = ["PySide6>=6.6.0"]

[project.urls]
Homepage = "https://github.com/leonardo201800478/mame-set-builder"
Repository = "https://github.com/leonardo201800478/mame-set-builder.git"
Issues = "https://github.com/leonardo201800478/mame-set-builder/issues"

[project.scripts]
mame-set-builder = "app.main:main"

[tool.setuptools.packages.find]
include = ["app*"]
exclude = ["tests*", "data*", "docs*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --tb=short"