PRAGMA foreign_keys = OFF;

-- xml_path is a locator, not the identity of an XML node.  The original
-- schema made it UNIQUE per import, which is an unnecessary restriction for a
-- lossless XML representation.
--
-- SQLite does not support dropping the UNIQUE constraint generated by
-- CREATE TABLE directly. Rebuild the table and repair the foreign-key SQL of
-- every dependent table. The data and node IDs are preserved.

DROP INDEX IF EXISTS ix_mame_xml_node_machine;
DROP INDEX IF EXISTS ix_mame_xml_node_element;
DROP INDEX IF EXISTS ix_mame_xml_node_path;

ALTER TABLE mame_xml_node RENAME TO mame_xml_node__old;

CREATE TABLE mame_xml_node (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    import_id INTEGER NOT NULL REFERENCES mame_listxml_import(id) ON DELETE CASCADE,
    parent_node_id INTEGER REFERENCES mame_xml_node(id) ON DELETE CASCADE,
    machine_id INTEGER,
    element_name TEXT NOT NULL,
    ordinal INTEGER NOT NULL DEFAULT 0,
    xml_path TEXT NOT NULL,
    text_value TEXT,
    attributes_json TEXT NOT NULL DEFAULT '{}'
);

INSERT INTO mame_xml_node
    (id, import_id, parent_node_id, machine_id, element_name, ordinal,
     xml_path, text_value, attributes_json)
SELECT
    id, import_id, parent_node_id, machine_id, element_name, ordinal,
    xml_path, text_value, attributes_json
FROM mame_xml_node__old;

-- ALTER TABLE RENAME rewrites FK declarations to the temporary table name.
-- Repair every table declaration that was automatically redirected.
PRAGMA writable_schema = ON;
UPDATE sqlite_master
SET sql = replace(sql, 'mame_xml_node__old', 'mame_xml_node')
WHERE type IN ('table', 'trigger', 'view')
  AND sql IS NOT NULL
  AND sql LIKE '%mame_xml_node__old%';
PRAGMA writable_schema = OFF;

DROP TABLE mame_xml_node__old;

CREATE INDEX IF NOT EXISTS ix_mame_xml_node_machine
    ON mame_xml_node(import_id, machine_id);
CREATE INDEX IF NOT EXISTS ix_mame_xml_node_element
    ON mame_xml_node(import_id, element_name);
CREATE INDEX IF NOT EXISTS ix_mame_xml_node_path
    ON mame_xml_node(import_id, xml_path);

-- Keep AUTOINCREMENT monotonic after the table rebuild.
UPDATE sqlite_sequence
SET seq = (SELECT COALESCE(MAX(id), 0) FROM mame_xml_node)
WHERE name = 'mame_xml_node';

PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO schema_migrations(version, applied_at)
VALUES ('009_mame_xml_node_remove_path_unique', datetime('now'));
